name: 构建镜像并推送到DockerHub
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v3

    - name: 登陆DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: 构建镜像并推送到DockerHub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: mobaia/react-app:latest