name: 打包React项目

on: push

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v3

    - name: 安装依赖
      run: npm install
    
    - name: 项目打包
      run: npm run build